### ISSUE TITLE
Status of this Repository

### ISSUE THREAD

**Issue by JWhitleyWork** [ros2/joystick_drivers#16]
@clalancette / @mikaelarguedas - Can you please comment on the status of this port and whether or not we want to merge it back into the original repository under `ros-drivers`?

**Comment by clalancette** [comment]
This is pretty stable; I haven't done any development on it in a while; I just released it into Eloquent with no changes.

Here are some reasons to keep it separate:

* We only did the port of the "joy" package; the rest are disabled via COLCON_IGNORE.
* The port is pretty basic; to be a "real" port, I'd want to substantially rewrite the thing so that it could be composed, etc.
* Laziness :).

But I honestly don't have a strong opinion about merging it back to the original or keeping it separate.  If there are good reasons to merge back with upstream, we could certainly do that.

**Comment by JWhitleyWork** [comment]
Thanks for the feedback! My primary reasoning would be to be able to manage bug fixes/feature additions in a single location. I am willing to do the reorganization work up-front on the ROS 1 version to create an easier port, if you (or someone else) would be willing to do some reviews. :) There are a few people that are interested in keeping the `ros-drivers` organization going so I would prefer it be there, if possible.

**Comment by JWhitleyWork** [comment]
So, to summarize, here are my arguments for merging it back to `ros-drivers`:

- Single CI connection
- Single management/maintainership group in Github
- Single location for issues that usually apply to both ROS1 and ROS2 versions
- Old wiki (highest result on Google for `joystick_drivers`) points to `ros-drivers` repo
- Single `release` repo in `ros-gbp` organization for all ROS versions

**Comment by clalancette** [comment]
Sure, that is totally fine with me.  I'm happy to do some reviews.  Just FYI that I likely won't get to any of it before the new year.

**Comment by JWhitleyWork** [comment]
Totally fine. I'll probably start before then but I won't expect any reviews before then. Thanks!
